### ISSUE TITLE
chrome: when pressing popup icon, it seems the request for category listing goes wrong sometimes.

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/wordCollector#38]
Started GET "/api/users/1" for 127.0.0.1 at 2015-08-28 23:24:57 +0900
[2015-08-28 23:24:57] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
    /Users/hiogawa/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:80:in `eof?'
    /Users/hiogawa/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:80:in`run'
    /Users/hiogawa/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
Processing by Api::V1::UsersController#show as JSON
  Parameters: {"id"=>"1"}
  User Load (0.4ms)  SELECT`users`.* FROM`users`WHERE`users`.`auth_token`= 'wMAi6EPK_rWRxzzbzYML' LIMIT 1
  User Load (0.3ms)  SELECT`users`.* FROM`users`WHERE`users`.`id`= 1 LIMIT 1
  Category Load (0.4ms)  SELECT`categories`.* FROM`categories`WHERE`categories`.`user_id` = 1
Completed 200 OK in 7ms (Views: 3.2ms | ActiveRecord: 1.1ms)

**Comment by hi-ogawa** [comment]
then backbone isn't loaded at all.

**Comment by hi-ogawa** [comment]
it doesn't happen on production, so I assume this is because of webrick or something?
- related to this? https://github.com/rails/rails/issues/18822
